[features]
seeds = false
[programs.localnet]
beacon_server = "FRoo7m8Sf6ZAirGgnn3KopQymDtujWx818kcnRxzi23b"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run test"
